services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5201:5432"
#    volumes:
#     - C:\Users\rakan\OneDrive\Desktop\interenSecyear\Clone
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: "WorkPLS"
      POSTGRES_HOST_AUTH_METHOD: trust
      PGTZ: UTC
      TZ: UTC