services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    ports:
      - "5201:5432"
    environment:
      POSTGRES_DB: WorkPLS
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d WorkPLS"]
      interval: 10s
      timeout: 3s
      retries: 10

  backend:
    image: kongsetthawut/todo-backend:latest
    container_name: backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/WorkPLS
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
