# =========================
# Backend
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: todolist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: backend
          image: docker.io/kongsetthawut/todo-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-svc:5432/WorkPLS
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: todolist
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - port: 8080
      targetPort: 8080

---
# =========================
# Frontend
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: todolist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/kongsetthawut/todo-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
  namespace: todolist
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081

---
# =========================
# Database (Postgres)
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: WorkPLS
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: todolist
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
